### ISSUE TITLE
Multi-Coin block behavior

### ISSUE THREAD

**Issue by maxoakland** [Mico27/SuperMarioBrosMini#13]
In this version, it seems that multi-coin blocks give you a set amount of coins. You can hit the block once, wait as long as you want, and it will still give you the same number of coins

In the original game, multi-coin blocks are on a timer. The faster you hit the block, the more coins you get. If you hit the block once and then wait, the next time you hit the block will give you a coin and then turn it solid so it can't be hit again

**Comment by Mico27** [comment]
Fixed the multi-coin behavior now to be time based like the og

**Comment by maxoakland** [comment]
> Fixed the multi-coin behavior now to be time based like the og

Awesome!!
