### ISSUE TITLE
Final Boss hand despawns beyond left side of screen

### ISSUE THREAD

**Issue by laytonloztew** [Mico27/SuperMarioBrosMini#17]
Version: 2.0.4

When up against the left side of the screen during the world 16 final boss fight, bowser will visually disappear. If he does a sweeping attack with the hand off-screen, it will despawn completely.

![bowserhand1](https://github.com/user-attachments/assets/d7944265-581e-45e9-a745-10056599c97d)
![bowserhand2](https://github.com/user-attachments/assets/0401c81e-581f-40a3-9e25-d985e1ea454d)

This can't be done on the right side of the screen

![2024-11-01T04-35-48Z](https://github.com/user-attachments/assets/08f6fe12-079b-4466-b0c6-d5cb50d1e2d2)

**Comment by Mico27** [comment]
Thanks again, fixed it so that it doesnt goes offscreen and the hands wont despawn
