### ISSUE TITLE
Attach below bottom of hanging vines, vine clip into ceiling

### ISSUE THREAD

**Issue by laytonloztew** [Mico27/SuperMarioBrosMini#18]
Version: 2.0.4

Mario tends to interact with the bottom of hanging vines strangely. 
In 12-1 hold Run and Left while attached to the vine in this position, press jump to consistently attach below the lower vine.
![2024-11-01T05-22-33Z](https://github.com/user-attachments/assets/28de78d3-c37e-42b6-8025-75b3b5d965bc)
![2024-11-01T05-22-35Z](https://github.com/user-attachments/assets/6f27604f-16d8-4375-b898-107b7d78c652)
Pressing Up in this state nudges Mario further down, and Down nudges him back up - but he cannot climb the vine. Jumping detaches as normal.

![2024-11-01T05-29-53Z](https://github.com/user-attachments/assets/f2999f7b-bacc-4a95-a14d-4ee96a90c99d)
![2024-11-01T05-29-55Z](https://github.com/user-attachments/assets/30f44027-e4af-45f5-9ab1-90d80e771225)
In 12-1 on this small vine at the top, Mario can clip into the pipe and get stuck by pressing Down then Jump.

**Comment by laytonloztew** [comment]
Just adding on to this one:

![2024-11-01T06-26-21Z](https://github.com/user-attachments/assets/5a01b36b-ac88-4d02-bc9f-36b2fb4f569e)
![2024-11-01T06-26-44Z](https://github.com/user-attachments/assets/1f2e6537-d731-4e8e-a335-09cb95a6632e)
Jump onto this vine at the top (aim for Mario text), climb offscreen and jump to die.

**Comment by Mico27** [comment]
Removed the problematics vines and "tried" to fix vines
