### ISSUE TITLE
World 8-2 long jump issue

### ISSUE THREAD

**Issue by nightwishfan1** [Mico27/SuperMarioBrosMini#21]
I've noticed a issue with the one sole long jump in world 8-2 each time I've attempted it so it should be easy to recreate.  The issue at hand is it should be able to be cleared either from running and jumping off the very edge of the warp pipe that is there, or taking the safe route and using the 2 ledges, but my issues comes up where Mario always falls short in your version when jumping off the edge of the pipe instead, and a few times the game has glitched where it seems he hits a invisible wall halfway over mid jump, and of course fails the jump.  Any other version of the game this jump is easy to accomplish despite it probably being easier using the two smaller ledges directly after the warp pipe, but for those that like speed playing by running almost constantly this a huge glitch that would turn them away by having to slow down.

**Comment by Mico27** [comment]
Thanks, I increased the Maximum speed to make it match closer to the OG, now those jumps are doable.
