### ISSUE TITLE
i was told to send this

### ISSUE THREAD

**Issue by manymasters** [Mico27/SuperMarioBrosMini#22]
Got this upon putting the new version on the Miyoo Mini Plus

![Super Mario Bros Mini_003](https://github.com/user-attachments/assets/c2fbc6a0-e26f-4d7d-a75c-3e19dacd1d9a)

**Comment by Mico27** [comment]
At which point upon playing it did the error pop up?

**Comment by manymasters** [comment]
Right when the game turns on, doesn't even make it to the title screen

**Comment by Mico27** [comment]
What kind of cart are you using?
Was a previous version of the game working before? If so, which version was it?

**Comment by manymasters** [comment]
Nevermind, my handheld was trying to load a save state from a prior version
so just resetting the rom fixed it.
Great work by the way, but just one thing, can you make it where 2
fireballs can be fired on screen at once like the NES game?
