### ISSUE TITLE
HELP! Invisible background

### ISSUE THREAD

**Issue by Tmasterxtreme** [Mico27/SuperMarioBrosMini#25]
I'm not the only one who has this problem but I can't figure out how to get the rest of the graphics to show, is there something I'm missing besides the ROM download?

![62972](https://github.com/user-attachments/assets/51313aa3-0920-4ce3-bc14-af277377fee9)

**Comment by Mico27** [comment]
Sorry, after investigating it, it looks like this is an hardware incompatibility issue with the FunKey S. It simply doesnt emulate the game correctly, so you'll have to either play it on a real gameboy color or some other hardware that support accurate gameboy color emulation.

**Comment by Tmasterxtreme** [comment]
Hold on, seems like it's working after I bricked my FunKey and had to reinstall with the latest version. If it can run SM64 then this tiny gizmo should never be underestimated.
![89871](https://github.com/user-attachments/assets/ebe87778-fe5a-4f50-9a44-b5a6fcb5bb4c)
