### ISSUE TITLE
Fire Flower Power Up

### ISSUE THREAD

**Issue by maxoakland** [Mico27/SuperMarioBrosMini#3]
Mario's fire flower powerup has a few issues

• Shoots at a different trajectory from the original game. It starts too high and/or doesn't move down fast enough before the first bounce. This makes some specific situations more difficult than the original game. Especially any instance where you're in close quarters with a goomba or koopa to get an item box like 4-2
• You can only shoot one fireball at a time. In the original you can shoot 2

**Comment by Mico27** [comment]
Although I kept the maximum fireball to 1 at a time, I changed the initial arc of the fireball to aim down like the OG (You can however still fire up like before by holding Up while firing)

**Comment by maxoakland** [comment]
> Although I kept the maximum fireball to 1 at a time, I changed the initial arc of the fireball to aim down like the OG (You can however still fire up like before by holding Up while firing)

I'm glad you changed the arc. Is there a technical reason for 1 fireball?

**Comment by Mico27** [comment]
Mainly because it uses an actor in GBStudio and I'm already pretty limited on actors, I could try to squeeze an extra actor for the second fireball but I'll have to go around all the scenes and add it as well as probably having to cull some enemies or other entities using an actor in scenes that already reached the actor limit to have a space for it.

**Comment by maxoakland** [comment]
> Mainly because it uses an actor in GBStudio and I'm already pretty limited on actors, I could try to squeeze an extra actor for the second fireball but I'll have to go around all the scenes and add it as well as probably having to cull some enemies or other entities using an actor in scenes that already reached the actor limit to have a space for it.

OK, that makes perfect sense. It seems like it's better to have the accurate enemies than adding the 2nd fireball

I wonder if it's possible to use the Projectile system for the fireballs. You can add projectiles on top of the normal enemy limit. You'd have to edit the code pretty heavily to enable the behavior of Mario's fireballs though (I think)

**Comment by Mico27** [comment]
Yeah I'd have to refactor how projectile works, also I'm at the point that I'd rather not do drastic changes to the engine right now. The game is pretty much in its final state and Someone is currently making retro achievements for the game and it'd break if I were to do an engine change that changes the memory map.

**Comment by maxoakland** [comment]
> Yeah I'd have to refactor how projectile works, also I'm at the point that I'd rather not do drastic changes to the engine right now. The game is pretty much in its final state and Someone is currently making retro achievements for the game and it'd break if I were to do an engine change that changes the memory map.

There is a custom projectile plugin that has a lot of options. Maybe that could work? https://nokotin.itch.io/custom-projectile-plugin
