### ISSUE TITLE
Physics Issues

### ISSUE THREAD

**Issue by maxoakland** [Mico27/SuperMarioBrosMini#4]
The physics are slightly different from the original game. This isn't usually an issue but there are some situations where it is

• Mario's friction seems to be higher than the original game. This affects sliding under blocks when mario is tall, swimming physics, and makes some platforming slightly easier
• In the original game if tall Mario slides under a block and stands up, the engine pushes him to the right. In this version, it's less predictable and usually seems to teleport him out of the collision toward the left
• Swimming: Mario moves too slowly horizontally and friction is too high

**Comment by nightwishfan1** [comment]
The swimming I agree on.  There was no fast swimming via holding B.  Mario moved faster by how you utilized the swim action, and kind of glided through the water after it's use was stopped.  That and the bloopers have too much a rubber band effect in catching back up to Mario when he does get away.  In other words they move faster then Mario.  In the original yes they were aggressive in later levels, but the swimming levels were more cat and mouse'ish type play.  You had a better chance of getting away and swimming around them.  Here you cannot, and you get nailed instead almost every time cause of the slowed swim movement.  It's pretty inaccurate in this regard.  I understand taking liberties with how the game works, but here it's a bit much.

**Comment by Mico27** [comment]
I tried reducing the friction and it didnt felt right so I kept it.
For the clipping, the way I coded the physics it works differently (You have to hold the opposite direction of where you want to be pushed back when clipped).
I changed the swimming to not having to hold B to swim faster and pressing A now adds a small horizontal boost.
Bloopers are also less aggressive now.
